# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fairfax/Devel/tunneler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fairfax/Devel/tunneler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fairfax/Devel/tunneler/CMakeFiles /home/fairfax/Devel/tunneler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fairfax/Devel/tunneler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tunneler_modules

# Build rule for target.
Tunneler_modules: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tunneler_modules
.PHONY : Tunneler_modules

# fast build rule for target.
Tunneler_modules/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/build
.PHONY : Tunneler_modules/fast

#=============================================================================
# Target rules for targets named tunneler

# Build rule for target.
tunneler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tunneler
.PHONY : tunneler

# fast build rule for target.
tunneler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tunneler.dir/build.make CMakeFiles/tunneler.dir/build
.PHONY : tunneler/fast

src/bullet.o: src/bullet.cc.o
.PHONY : src/bullet.o

# target to build an object file
src/bullet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/bullet.cc.o
.PHONY : src/bullet.cc.o

src/bullet.i: src/bullet.cc.i
.PHONY : src/bullet.i

# target to preprocess a source file
src/bullet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/bullet.cc.i
.PHONY : src/bullet.cc.i

src/bullet.s: src/bullet.cc.s
.PHONY : src/bullet.s

# target to generate assembly for a file
src/bullet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/bullet.cc.s
.PHONY : src/bullet.cc.s

src/camera.o: src/camera.cc.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/camera.cc.o
.PHONY : src/camera.cc.o

src/camera.i: src/camera.cc.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/camera.cc.i
.PHONY : src/camera.cc.i

src/camera.s: src/camera.cc.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/camera.cc.s
.PHONY : src/camera.cc.s

src/collisions.o: src/collisions.cc.o
.PHONY : src/collisions.o

# target to build an object file
src/collisions.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/collisions.cc.o
.PHONY : src/collisions.cc.o

src/collisions.i: src/collisions.cc.i
.PHONY : src/collisions.i

# target to preprocess a source file
src/collisions.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/collisions.cc.i
.PHONY : src/collisions.cc.i

src/collisions.s: src/collisions.cc.s
.PHONY : src/collisions.s

# target to generate assembly for a file
src/collisions.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/collisions.cc.s
.PHONY : src/collisions.cc.s

src/commondef.o: src/commondef.cc.o
.PHONY : src/commondef.o

# target to build an object file
src/commondef.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/commondef.cc.o
.PHONY : src/commondef.cc.o

src/commondef.i: src/commondef.cc.i
.PHONY : src/commondef.i

# target to preprocess a source file
src/commondef.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/commondef.cc.i
.PHONY : src/commondef.cc.i

src/commondef.s: src/commondef.cc.s
.PHONY : src/commondef.s

# target to generate assembly for a file
src/commondef.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/commondef.cc.s
.PHONY : src/commondef.cc.s

src/game.o: src/game.cc.o
.PHONY : src/game.o

# target to build an object file
src/game.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/game.cc.o
.PHONY : src/game.cc.o

src/game.i: src/game.cc.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/game.cc.i
.PHONY : src/game.cc.i

src/game.s: src/game.cc.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/game.cc.s
.PHONY : src/game.cc.s

src/initvect.o: src/initvect.cc.o
.PHONY : src/initvect.o

# target to build an object file
src/initvect.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/initvect.cc.o
.PHONY : src/initvect.cc.o

src/initvect.i: src/initvect.cc.i
.PHONY : src/initvect.i

# target to preprocess a source file
src/initvect.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/initvect.cc.i
.PHONY : src/initvect.cc.i

src/initvect.s: src/initvect.cc.s
.PHONY : src/initvect.s

# target to generate assembly for a file
src/initvect.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/initvect.cc.s
.PHONY : src/initvect.cc.s

src/mirror.o: src/mirror.cc.o
.PHONY : src/mirror.o

# target to build an object file
src/mirror.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/mirror.cc.o
.PHONY : src/mirror.cc.o

src/mirror.i: src/mirror.cc.i
.PHONY : src/mirror.i

# target to preprocess a source file
src/mirror.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/mirror.cc.i
.PHONY : src/mirror.cc.i

src/mirror.s: src/mirror.cc.s
.PHONY : src/mirror.s

# target to generate assembly for a file
src/mirror.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/mirror.cc.s
.PHONY : src/mirror.cc.s

src/painting.o: src/painting.cc.o
.PHONY : src/painting.o

# target to build an object file
src/painting.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/painting.cc.o
.PHONY : src/painting.cc.o

src/painting.i: src/painting.cc.i
.PHONY : src/painting.i

# target to preprocess a source file
src/painting.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/painting.cc.i
.PHONY : src/painting.cc.i

src/painting.s: src/painting.cc.s
.PHONY : src/painting.s

# target to generate assembly for a file
src/painting.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/painting.cc.s
.PHONY : src/painting.cc.s

src/player.o: src/player.cc.o
.PHONY : src/player.o

# target to build an object file
src/player.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/player.cc.o
.PHONY : src/player.cc.o

src/player.i: src/player.cc.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/player.cc.i
.PHONY : src/player.cc.i

src/player.s: src/player.cc.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/player.cc.s
.PHONY : src/player.cc.s

src/statusbar.o: src/statusbar.cc.o
.PHONY : src/statusbar.o

# target to build an object file
src/statusbar.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/statusbar.cc.o
.PHONY : src/statusbar.cc.o

src/statusbar.i: src/statusbar.cc.i
.PHONY : src/statusbar.i

# target to preprocess a source file
src/statusbar.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/statusbar.cc.i
.PHONY : src/statusbar.cc.i

src/statusbar.s: src/statusbar.cc.s
.PHONY : src/statusbar.s

# target to generate assembly for a file
src/statusbar.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/statusbar.cc.s
.PHONY : src/statusbar.cc.s

src/structure.o: src/structure.cc.o
.PHONY : src/structure.o

# target to build an object file
src/structure.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/structure.cc.o
.PHONY : src/structure.cc.o

src/structure.i: src/structure.cc.i
.PHONY : src/structure.i

# target to preprocess a source file
src/structure.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/structure.cc.i
.PHONY : src/structure.cc.i

src/structure.s: src/structure.cc.s
.PHONY : src/structure.s

# target to generate assembly for a file
src/structure.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/structure.cc.s
.PHONY : src/structure.cc.s

src/tank.o: src/tank.cc.o
.PHONY : src/tank.o

# target to build an object file
src/tank.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/tank.cc.o
.PHONY : src/tank.cc.o

src/tank.i: src/tank.cc.i
.PHONY : src/tank.i

# target to preprocess a source file
src/tank.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/tank.cc.i
.PHONY : src/tank.cc.i

src/tank.s: src/tank.cc.s
.PHONY : src/tank.s

# target to generate assembly for a file
src/tank.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/tank.cc.s
.PHONY : src/tank.cc.s

src/tmap.o: src/tmap.cc.o
.PHONY : src/tmap.o

# target to build an object file
src/tmap.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/tmap.cc.o
.PHONY : src/tmap.cc.o

src/tmap.i: src/tmap.cc.i
.PHONY : src/tmap.i

# target to preprocess a source file
src/tmap.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/tmap.cc.i
.PHONY : src/tmap.cc.i

src/tmap.s: src/tmap.cc.s
.PHONY : src/tmap.s

# target to generate assembly for a file
src/tmap.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tunneler_modules.dir/build.make CMakeFiles/Tunneler_modules.dir/src/tmap.cc.s
.PHONY : src/tmap.cc.s

src/tunneler.o: src/tunneler.cc.o
.PHONY : src/tunneler.o

# target to build an object file
src/tunneler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tunneler.dir/build.make CMakeFiles/tunneler.dir/src/tunneler.cc.o
.PHONY : src/tunneler.cc.o

src/tunneler.i: src/tunneler.cc.i
.PHONY : src/tunneler.i

# target to preprocess a source file
src/tunneler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tunneler.dir/build.make CMakeFiles/tunneler.dir/src/tunneler.cc.i
.PHONY : src/tunneler.cc.i

src/tunneler.s: src/tunneler.cc.s
.PHONY : src/tunneler.s

# target to generate assembly for a file
src/tunneler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tunneler.dir/build.make CMakeFiles/tunneler.dir/src/tunneler.cc.s
.PHONY : src/tunneler.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tunneler_modules"
	@echo "... tunneler"
	@echo "... src/bullet.o"
	@echo "... src/bullet.i"
	@echo "... src/bullet.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/collisions.o"
	@echo "... src/collisions.i"
	@echo "... src/collisions.s"
	@echo "... src/commondef.o"
	@echo "... src/commondef.i"
	@echo "... src/commondef.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/initvect.o"
	@echo "... src/initvect.i"
	@echo "... src/initvect.s"
	@echo "... src/mirror.o"
	@echo "... src/mirror.i"
	@echo "... src/mirror.s"
	@echo "... src/painting.o"
	@echo "... src/painting.i"
	@echo "... src/painting.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/statusbar.o"
	@echo "... src/statusbar.i"
	@echo "... src/statusbar.s"
	@echo "... src/structure.o"
	@echo "... src/structure.i"
	@echo "... src/structure.s"
	@echo "... src/tank.o"
	@echo "... src/tank.i"
	@echo "... src/tank.s"
	@echo "... src/tmap.o"
	@echo "... src/tmap.i"
	@echo "... src/tmap.s"
	@echo "... src/tunneler.o"
	@echo "... src/tunneler.i"
	@echo "... src/tunneler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

